//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.586
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacman.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pacman.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap afraidGhost1 {
            get {
                object obj = ResourceManager.GetObject("afraidGhost1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhost2 {
            get {
                object obj = ResourceManager.GetObject("afraidGhost2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhost3 {
            get {
                object obj = ResourceManager.GetObject("afraidGhost3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhost4 {
            get {
                object obj = ResourceManager.GetObject("afraidGhost4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhost5 {
            get {
                object obj = ResourceManager.GetObject("afraidGhost5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhost6 {
            get {
                object obj = ResourceManager.GetObject("afraidGhost6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhostEnd1 {
            get {
                object obj = ResourceManager.GetObject("afraidGhostEnd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhostEnd2 {
            get {
                object obj = ResourceManager.GetObject("afraidGhostEnd2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhostEnd3 {
            get {
                object obj = ResourceManager.GetObject("afraidGhostEnd3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhostEnd4 {
            get {
                object obj = ResourceManager.GetObject("afraidGhostEnd4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhostEnd5 {
            get {
                object obj = ResourceManager.GetObject("afraidGhostEnd5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap afraidGhostEnd6 {
            get {
                object obj = ResourceManager.GetObject("afraidGhostEnd6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky1Down {
            get {
                object obj = ResourceManager.GetObject("blinky1Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky1Left {
            get {
                object obj = ResourceManager.GetObject("blinky1Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky1Right {
            get {
                object obj = ResourceManager.GetObject("blinky1Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky1Up {
            get {
                object obj = ResourceManager.GetObject("blinky1Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky2Down {
            get {
                object obj = ResourceManager.GetObject("blinky2Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky2Left {
            get {
                object obj = ResourceManager.GetObject("blinky2Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky2Right {
            get {
                object obj = ResourceManager.GetObject("blinky2Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky2Up {
            get {
                object obj = ResourceManager.GetObject("blinky2Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky3Down {
            get {
                object obj = ResourceManager.GetObject("blinky3Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky3Left {
            get {
                object obj = ResourceManager.GetObject("blinky3Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky3Right {
            get {
                object obj = ResourceManager.GetObject("blinky3Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky3Up {
            get {
                object obj = ResourceManager.GetObject("blinky3Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky4Down {
            get {
                object obj = ResourceManager.GetObject("blinky4Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky4Left {
            get {
                object obj = ResourceManager.GetObject("blinky4Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky4Right {
            get {
                object obj = ResourceManager.GetObject("blinky4Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky4Up {
            get {
                object obj = ResourceManager.GetObject("blinky4Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky5Down {
            get {
                object obj = ResourceManager.GetObject("blinky5Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky5Left {
            get {
                object obj = ResourceManager.GetObject("blinky5Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky5Right {
            get {
                object obj = ResourceManager.GetObject("blinky5Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky5Up {
            get {
                object obj = ResourceManager.GetObject("blinky5Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky6Down {
            get {
                object obj = ResourceManager.GetObject("blinky6Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky6Left {
            get {
                object obj = ResourceManager.GetObject("blinky6Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky6Right {
            get {
                object obj = ResourceManager.GetObject("blinky6Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blinky6Up {
            get {
                object obj = ResourceManager.GetObject("blinky6Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde1Down {
            get {
                object obj = ResourceManager.GetObject("clyde1Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde1Left {
            get {
                object obj = ResourceManager.GetObject("clyde1Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde1Right {
            get {
                object obj = ResourceManager.GetObject("clyde1Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde1Up {
            get {
                object obj = ResourceManager.GetObject("clyde1Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde2Down {
            get {
                object obj = ResourceManager.GetObject("clyde2Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde2Left {
            get {
                object obj = ResourceManager.GetObject("clyde2Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde2Right {
            get {
                object obj = ResourceManager.GetObject("clyde2Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde2Up {
            get {
                object obj = ResourceManager.GetObject("clyde2Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde3Down {
            get {
                object obj = ResourceManager.GetObject("clyde3Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde3Left {
            get {
                object obj = ResourceManager.GetObject("clyde3Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde3Right {
            get {
                object obj = ResourceManager.GetObject("clyde3Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde3Up {
            get {
                object obj = ResourceManager.GetObject("clyde3Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde4Down {
            get {
                object obj = ResourceManager.GetObject("clyde4Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde4Left {
            get {
                object obj = ResourceManager.GetObject("clyde4Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde4Right {
            get {
                object obj = ResourceManager.GetObject("clyde4Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde4Up {
            get {
                object obj = ResourceManager.GetObject("clyde4Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde5Down {
            get {
                object obj = ResourceManager.GetObject("clyde5Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde5Left {
            get {
                object obj = ResourceManager.GetObject("clyde5Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde5Right {
            get {
                object obj = ResourceManager.GetObject("clyde5Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde5Up {
            get {
                object obj = ResourceManager.GetObject("clyde5Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde6Down {
            get {
                object obj = ResourceManager.GetObject("clyde6Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde6Left {
            get {
                object obj = ResourceManager.GetObject("clyde6Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde6Right {
            get {
                object obj = ResourceManager.GetObject("clyde6Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clyde6Up {
            get {
                object obj = ResourceManager.GetObject("clyde6Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream eat_ghost {
            get {
                return ResourceManager.GetStream("eat_ghost", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream eat_pill {
            get {
                return ResourceManager.GetStream("eat_pill", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream eat_pow {
            get {
                return ResourceManager.GetStream("eat_pow", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream extra_lives {
            get {
                return ResourceManager.GetStream("extra_lives", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap eyesDown {
            get {
                object obj = ResourceManager.GetObject("eyesDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyesLeft {
            get {
                object obj = ResourceManager.GetObject("eyesLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyesRight {
            get {
                object obj = ResourceManager.GetObject("eyesRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyesUp {
            get {
                object obj = ResourceManager.GetObject("eyesUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky1Down {
            get {
                object obj = ResourceManager.GetObject("inky1Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky1Left {
            get {
                object obj = ResourceManager.GetObject("inky1Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky1Right {
            get {
                object obj = ResourceManager.GetObject("inky1Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky1Up {
            get {
                object obj = ResourceManager.GetObject("inky1Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky2Down {
            get {
                object obj = ResourceManager.GetObject("inky2Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky2Left {
            get {
                object obj = ResourceManager.GetObject("inky2Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky2Right {
            get {
                object obj = ResourceManager.GetObject("inky2Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky2Up {
            get {
                object obj = ResourceManager.GetObject("inky2Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky3Down {
            get {
                object obj = ResourceManager.GetObject("inky3Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky3Left {
            get {
                object obj = ResourceManager.GetObject("inky3Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky3Right {
            get {
                object obj = ResourceManager.GetObject("inky3Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky3Up {
            get {
                object obj = ResourceManager.GetObject("inky3Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky4Down {
            get {
                object obj = ResourceManager.GetObject("inky4Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky4Left {
            get {
                object obj = ResourceManager.GetObject("inky4Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky4Right {
            get {
                object obj = ResourceManager.GetObject("inky4Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky4Up {
            get {
                object obj = ResourceManager.GetObject("inky4Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky5Down {
            get {
                object obj = ResourceManager.GetObject("inky5Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky5Left {
            get {
                object obj = ResourceManager.GetObject("inky5Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky5Right {
            get {
                object obj = ResourceManager.GetObject("inky5Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky5Up {
            get {
                object obj = ResourceManager.GetObject("inky5Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky6Down {
            get {
                object obj = ResourceManager.GetObject("inky6Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky6Left {
            get {
                object obj = ResourceManager.GetObject("inky6Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky6Right {
            get {
                object obj = ResourceManager.GetObject("inky6Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inky6Up {
            get {
                object obj = ResourceManager.GetObject("inky6Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream morto {
            get {
                return ResourceManager.GetStream("morto", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap pac {
            get {
                object obj = ResourceManager.GetObject("pac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman10Down {
            get {
                object obj = ResourceManager.GetObject("pacman10Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman10Left {
            get {
                object obj = ResourceManager.GetObject("pacman10Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman10Right {
            get {
                object obj = ResourceManager.GetObject("pacman10Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman10Up {
            get {
                object obj = ResourceManager.GetObject("pacman10Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman11Down {
            get {
                object obj = ResourceManager.GetObject("pacman11Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman11Left {
            get {
                object obj = ResourceManager.GetObject("pacman11Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman11Right {
            get {
                object obj = ResourceManager.GetObject("pacman11Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman11Up {
            get {
                object obj = ResourceManager.GetObject("pacman11Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman12Down {
            get {
                object obj = ResourceManager.GetObject("pacman12Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman12Left {
            get {
                object obj = ResourceManager.GetObject("pacman12Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman12Right {
            get {
                object obj = ResourceManager.GetObject("pacman12Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman12Up {
            get {
                object obj = ResourceManager.GetObject("pacman12Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman13Down {
            get {
                object obj = ResourceManager.GetObject("pacman13Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman13Left {
            get {
                object obj = ResourceManager.GetObject("pacman13Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman13Right {
            get {
                object obj = ResourceManager.GetObject("pacman13Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman13Up {
            get {
                object obj = ResourceManager.GetObject("pacman13Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman14Down {
            get {
                object obj = ResourceManager.GetObject("pacman14Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman14Left {
            get {
                object obj = ResourceManager.GetObject("pacman14Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman14Right {
            get {
                object obj = ResourceManager.GetObject("pacman14Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman14Up {
            get {
                object obj = ResourceManager.GetObject("pacman14Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman1Down {
            get {
                object obj = ResourceManager.GetObject("pacman1Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman1Left {
            get {
                object obj = ResourceManager.GetObject("pacman1Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman1Right {
            get {
                object obj = ResourceManager.GetObject("pacman1Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman1Up {
            get {
                object obj = ResourceManager.GetObject("pacman1Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman2Down {
            get {
                object obj = ResourceManager.GetObject("pacman2Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman2Left {
            get {
                object obj = ResourceManager.GetObject("pacman2Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman2Right {
            get {
                object obj = ResourceManager.GetObject("pacman2Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman2Up {
            get {
                object obj = ResourceManager.GetObject("pacman2Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman3Down {
            get {
                object obj = ResourceManager.GetObject("pacman3Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman3Left {
            get {
                object obj = ResourceManager.GetObject("pacman3Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman3Right {
            get {
                object obj = ResourceManager.GetObject("pacman3Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman3Up {
            get {
                object obj = ResourceManager.GetObject("pacman3Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman4Down {
            get {
                object obj = ResourceManager.GetObject("pacman4Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman4Left {
            get {
                object obj = ResourceManager.GetObject("pacman4Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman4Right {
            get {
                object obj = ResourceManager.GetObject("pacman4Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman4Up {
            get {
                object obj = ResourceManager.GetObject("pacman4Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman5Down {
            get {
                object obj = ResourceManager.GetObject("pacman5Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman5Left {
            get {
                object obj = ResourceManager.GetObject("pacman5Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman5Right {
            get {
                object obj = ResourceManager.GetObject("pacman5Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman5Up {
            get {
                object obj = ResourceManager.GetObject("pacman5Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman6Down {
            get {
                object obj = ResourceManager.GetObject("pacman6Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman6Left {
            get {
                object obj = ResourceManager.GetObject("pacman6Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman6Right {
            get {
                object obj = ResourceManager.GetObject("pacman6Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman6Up {
            get {
                object obj = ResourceManager.GetObject("pacman6Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman7Down {
            get {
                object obj = ResourceManager.GetObject("pacman7Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman7Left {
            get {
                object obj = ResourceManager.GetObject("pacman7Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman7Right {
            get {
                object obj = ResourceManager.GetObject("pacman7Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman7Up {
            get {
                object obj = ResourceManager.GetObject("pacman7Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman8Down {
            get {
                object obj = ResourceManager.GetObject("pacman8Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman8Left {
            get {
                object obj = ResourceManager.GetObject("pacman8Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman8Right {
            get {
                object obj = ResourceManager.GetObject("pacman8Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman8Up {
            get {
                object obj = ResourceManager.GetObject("pacman8Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman9Down {
            get {
                object obj = ResourceManager.GetObject("pacman9Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman9Left {
            get {
                object obj = ResourceManager.GetObject("pacman9Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman9Right {
            get {
                object obj = ResourceManager.GetObject("pacman9Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pacman9Up {
            get {
                object obj = ResourceManager.GetObject("pacman9Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pause2 {
            get {
                object obj = ResourceManager.GetObject("pause2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pill {
            get {
                object obj = ResourceManager.GetObject("pill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky1Down {
            get {
                object obj = ResourceManager.GetObject("pinky1Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky1Left {
            get {
                object obj = ResourceManager.GetObject("pinky1Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky1Right {
            get {
                object obj = ResourceManager.GetObject("pinky1Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky1Up {
            get {
                object obj = ResourceManager.GetObject("pinky1Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky2Down {
            get {
                object obj = ResourceManager.GetObject("pinky2Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky2Left {
            get {
                object obj = ResourceManager.GetObject("pinky2Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky2Right {
            get {
                object obj = ResourceManager.GetObject("pinky2Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky2Up {
            get {
                object obj = ResourceManager.GetObject("pinky2Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky3Down {
            get {
                object obj = ResourceManager.GetObject("pinky3Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky3Left {
            get {
                object obj = ResourceManager.GetObject("pinky3Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky3Right {
            get {
                object obj = ResourceManager.GetObject("pinky3Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky3Up {
            get {
                object obj = ResourceManager.GetObject("pinky3Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky4Down {
            get {
                object obj = ResourceManager.GetObject("pinky4Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky4Left {
            get {
                object obj = ResourceManager.GetObject("pinky4Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky4Right {
            get {
                object obj = ResourceManager.GetObject("pinky4Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky4Up {
            get {
                object obj = ResourceManager.GetObject("pinky4Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky5Down {
            get {
                object obj = ResourceManager.GetObject("pinky5Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky5Left {
            get {
                object obj = ResourceManager.GetObject("pinky5Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky5Right {
            get {
                object obj = ResourceManager.GetObject("pinky5Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky5Up {
            get {
                object obj = ResourceManager.GetObject("pinky5Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky6Down {
            get {
                object obj = ResourceManager.GetObject("pinky6Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky6Left {
            get {
                object obj = ResourceManager.GetObject("pinky6Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky6Right {
            get {
                object obj = ResourceManager.GetObject("pinky6Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pinky6Up {
            get {
                object obj = ResourceManager.GetObject("pinky6Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap play2 {
            get {
                object obj = ResourceManager.GetObject("play2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap refresh2 {
            get {
                object obj = ResourceManager.GetObject("refresh2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream ridere {
            get {
                return ResourceManager.GetStream("ridere", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap setting2 {
            get {
                object obj = ResourceManager.GetObject("setting2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap specialPill {
            get {
                object obj = ResourceManager.GetObject("specialPill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream start {
            get {
                return ResourceManager.GetStream("start", resourceCulture);
            }
        }
        
        public static byte[] WhimsyTT {
            get {
                object obj = ResourceManager.GetObject("WhimsyTT", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
